name: tmdb_repository
description: A Dart package for The Movie Database domain.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  tmdb_api:
    path: ../tmdb_api
  equatable: ^1.2.5
  meta: ^1.2.3
