name: tmdb_api
description: A Dart API Client for The Movie Database API
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0

